In [15]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder,StandardScaler

In [7]:
data = pd.read_excel('/Users/haitonghuang/Downloads/Date_Fruit_Datasets/Date_Fruit_Datasets.xlsx')
data.head(20)

AREA  PERIMETER  MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY   EQDIASQ  \
0   422163  2378.9080    837.8484    645.6693        0.6373  733.1539   
1   338136  2085.1440    723.8198    595.2073        0.5690  656.1464   
2   526843  2647.3940    940.7379    715.3638        0.6494  819.0222   
3   416063  2351.2100    827.9804    645.2988        0.6266  727.8378   
4   347562  2160.3540    763.9877    582.8359        0.6465  665.2291   
5   408953  2326.6931    840.1821    622.0076        0.6722  721.5921   
6   451414  2457.2080    889.3253    652.4316        0.6796  758.1281   
7   382636  2275.7791    808.0833    609.2819        0.6569  697.9880   
8   546063  2714.9480    916.3737    766.4536        0.5481  833.8279   
9   420044  2391.1230    836.9280    645.1822        0.6370  731.3116   
10  364495  2216.4900    790.9014    590.7698        0.6649  681.2411   
11  404243  2345.5349    823.7634    628.8527        0.6459  717.4247   
12  407789  2308.4099    788.7270    664.5451        0.5386  720.5644   
13  340451  2098.1631    724.4111    600.3284        0.5597  658.3887   
14  467092  2514.2429    895.3616    669.6182        0.6638  771.1809   
15  386374  2265.6660    826.3535    597.2911        0.6911  701.3891   
16  413069  2350.4109    821.2114    645.8047        0.6177  725.2143   
17  396792  2291.0701    790.0845    644.6891        0.5781  710.7822   
18  358545  2199.5081    775.7432    593.7310        0.6436  675.6580   
19  397744  2337.2251    869.5142    583.9490        0.7409  711.6343   

    SOLIDITY  CONVEX_AREA  EXTENT  ASPECT_RATIO  ...  KurtosisRR  KurtosisRG  \
0     0.9947       424428  0.7831        1.2976  ...      3.2370      2.9574   
1     0.9974       339014  0.7795        1.2161  ...      2.6228      2.6350   
2     0.9962       528876  0.7657        1.3150  ...      3.7516      3.8611   
3     0.9948       418255  0.7759        1.2831  ...      5.0401      8.6136   
4     0.9908       350797  0.7569        1.3108  ...      2.7016      2.9761   
5     0.9974       410036  0.7805        1.3508  ...      3.6309      6.0285   
6     0.9970       452755  0.7877        1.3631  ...      3.0703      3.4163   
7     0.9931       385277  0.7032        1.3263  ...      3.6756      7.0258   
8     0.9882       552598  0.7710        1.1956  ...      3.4640      3.7416   
9     0.9918       423531  0.7853        1.2972  ...      3.3729      4.2898   
10    0.9949       366374  0.7658        1.3388  ...      3.0514      4.3653   
11    0.9921       407460  0.7808        1.3099  ...      3.0224      4.7019   
12    0.9958       409514  0.7594        1.1869  ...      3.4429      4.0735   
13    0.9971       341437  0.7813        1.2067  ...      2.4762      2.7434   
14    0.9946       469638  0.8036        1.3371  ...      3.8104      5.5369   
15    0.9968       387604  0.7588        1.3835  ...      2.1798      2.8977   
16    0.9917       416536  0.7485        1.2716  ...      3.3222      4.7191   
17    0.9967       398109  0.7372        1.2255  ...      2.8394      4.4264   
18    0.9911       361776  0.7306        1.3066  ...      3.6705      4.9932   
19    0.9947       399862  0.7648        1.4890  ...      3.8692      4.9534   

    KurtosisRB    EntropyRR    EntropyRG    EntropyRB  ALLdaub4RR  ALLdaub4RG  \
0       4.2287 -59191263232 -50714214400 -39922372608     58.7255     54.9554   
1       3.1704 -34233065472 -37462601728 -31477794816     50.0259     52.8168   
2       4.7192 -93948354560 -74738221056 -60311207936     65.4772     59.2860   
3       8.2618 -32074307584 -32060925952 -29575010304     43.3900     44.1259   
4       4.4146 -39980974080 -35980042240 -25593278464     52.7743     50.9080   
5       6.2159 -41140371456 -33146710016 -27907301376     49.7001     45.3190   
6       4.9168 -63711666176 -64060743680 -52603465728     57.8060     58.5449   
7       5.3254 -29873577984 -33570080768 -33054025728     45.1768     48.2407   
8       4.8120 -95262416896 -79321833472 -69569445888     64.6

In [20]:
data.describe()

AREA    PERIMETER   MAJOR_AXIS  MINOR_AXIS  ECCENTRICITY  \
count     898.000000   898.000000   898.000000  898.000000    898.000000   
mean   298295.207127  2057.660953   750.811994  495.872785      0.737468   
std    107245.205337   410.012459   144.059326  114.268917      0.088727   
min      1987.000000   911.828000   336.722700    2.283200      0.344800   
25%    206948.000000  1726.091500   641.068650  404.684375      0.685625   
50%    319833.000000  2196.345450   791.363400  495.054850      0.754700   
75%    382573.000000  2389.716575   858.633750  589.031700      0.802150   
max    546063.000000  2811.997100  1222.723000  766.453600      1.000000   

          EQDIASQ    SOLIDITY    CONVEX_AREA      EXTENT  ASPECT_RATIO  ...  \
count  898.000000  898.000000     898.000000  898.000000    898.000000  ...   
mean   604.577938    0.981840  303845.592428    0.736267      2.131102  ...   
std    119.593888    0.018157  108815.656947    0.053745     17.820778  ...   
min     50.298400    0.836600    2257.000000    0.512300      1.065300  ...   
25%    513.317075    0.978825  210022.750000    0.705875      1.373725  ...   
50%    638.140950    0.987300  327207.000000    0.746950      1.524150  ...   
75%    697.930525    0.991800  388804.000000    0.775850      1.674750  ...   
max    833.827900    0.997400  552598.000000    0.856200    535.525700  ...   

       KurtosisRR  KurtosisRG  KurtosisRB     EntropyRR     EntropyRG  \
count  898.000000  898.000000  898.000000  8.980000e+02  8.980000e+02   
mean     4.247845    5.110894    3.780928 -3.185021e+10 -2.901860e+10   
std      2.892357    3.745463    2.049831  2.037241e+10  1.712952e+10   
min      1.708200    1.607600    1.767200 -1.091224e+11 -9.261697e+10   
25%      2.536625    2.508850    2.577275 -4.429444e+10 -3.894638e+10   
50%      3.069800    3.127800    3.080700 -2.826156e+10 -2.620990e+10   
75%      4.449850    7.320400    4.283125 -1.460482e+10 -1.433105e+10   
max     26.171100   26.736700   32.249500 -1.627316e+08 -5.627727e+08   

          EntropyRB  ALLdaub4RR  ALLdaub4RG  ALLdaub4RB       Class  
count  8.980000e+02  898.000000  898.000000  898.000000  898.000000  
mean  -2.771876e+10   50.082888   48.805681   48.098393    3.279510  
std    1.484137e+10   16.063125   14.125911   10.813862    1.803886  
min   -8.747177e+10   15.191100   20.524700   22.130000    0.000000  
25%   -3.564534e+10   38.224425   38.654525   39.250725    2.000000  
50%   -2.392928e+10   53.841300   50.337800   49.614100    4.000000  
75%   -1.660367e+10   63.063350   59.573600   56.666675    5.000000  
max   -4.370435e+08   79.828900   83.064900   74.104600    6.000000  

[8 rows x 35 columns]

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 898 entries, 0 to 897
Data columns (total 35 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   AREA           898 non-null    int64  
 1   PERIMETER      898 non-null    float64
 2   MAJOR_AXIS     898 non-null    float64
 3   MINOR_AXIS     898 non-null    float64
 4   ECCENTRICITY   898 non-null    float64
 5   EQDIASQ        898 non-null    float64
 6   SOLIDITY       898 non-null    float64
 7   CONVEX_AREA    898 non-null    int64  
 8   EXTENT         898 non-null    float64
 9   ASPECT_RATIO   898 non-null    float64
 10  ROUNDNESS      898 non-null    float64
 11  COMPACTNESS    898 non-null    float64
 12  SHAPEFACTOR_1  898 non-null    float64
 13  SHAPEFACTOR_2  898 non-null    float64
 14  SHAPEFACTOR_3  898 non-null    float64
 15  SHAPEFACTOR_4  898 non-null    float64
 16  MeanRR         898 non-null    float64
 17  MeanRG         898 non-null    float64
 18  MeanRB    

In [22]:
data.Class.value_counts()

2    204
5    199
4    166
1     98
6     94
3     72
0     65
Name: Class, dtype: int64

In [25]:
x = data.drop('Class',axis=1).to_numpy()
y = data['Class'].to_numpy()

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x, y, stratify=y,test_size=0.2,random_state=100)

This stratify parameter makes a split so that the proportion of values in the sample produced will be the same as the proportion of values provided to parameter stratify.

For example, if variable y is a binary categorical variable with values 0 and 1 and there are 25% of zeros and 75% of ones, stratify=y will make sure that your random split has 25% of 0's and 75% of 1's.

In [27]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train2 = sc.fit_transform(x_train)
x_test2 = sc.transform(x_test)

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix

for name,method in [('DT', DecisionTreeClassifier(random_state=100))]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    target_names=['DOKOL','SAFAVI','ROTANA','DEGLET','SOGAY','IRAQI','BERHI']
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict,target_names=target_names))


Estimator: DT
[[ 9  0  0  4  0  0  0]
 [ 0 12  6  0  0  0  2]
 [ 0  3 37  1  0  0  0]
 [ 5  0  0  7  1  1  0]
 [ 0  2  0  0 30  0  1]
 [ 0  0  0  0  0 39  1]
 [ 0  3  0  0  0  1 15]]
              precision    recall  f1-score   support

       DOKOL       0.64      0.69      0.67        13
      SAFAVI       0.60      0.60      0.60        20
      ROTANA       0.86      0.90      0.88        41
      DEGLET       0.58      0.50      0.54        14
       SOGAY       0.97      0.91      0.94        33
       IRAQI       0.95      0.97      0.96        40
       BERHI       0.79      0.79      0.79        19

    accuracy                           0.83       180
   macro avg       0.77      0.77      0.77       180
weighted avg       0.83      0.83      0.83       180



In [29]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix  

for name,method in [('SVM', SVC(kernel='linear',random_state=100))]: 
    method.fit(x_train2,y_train)
    predict = method.predict(x_test2)
    target_names=['DOKOL','SAFAVI','ROTANA','DEGLET','SOGAY','IRAQI','BERHI']
    print('\nEstimator: {}'.format(name)) 
    print(confusion_matrix(y_test,predict))  
    print(classification_report(y_test,predict,target_names=target_names))


Estimator: SVM
[[11  0  0  1  1  0  0]
 [ 0 14  5  0  0  0  1]
 [ 0  0 41  0  0  0  0]
 [ 2  0  0 12  0  0  0]
 [ 0  1  0  0 31  0  1]
 [ 0  0  0  0  0 40  0]
 [ 0  2  0  0  1  0 16]]
              precision    recall  f1-score   support

       DOKOL       0.85      0.85      0.85        13
      SAFAVI       0.82      0.70      0.76        20
      ROTANA       0.89      1.00      0.94        41
      DEGLET       0.92      0.86      0.89        14
       SOGAY       0.94      0.94      0.94        33
       IRAQI       1.00      1.00      1.00        40
       BERHI       0.89      0.84      0.86        19

    accuracy                           0.92       180
   macro avg       0.90      0.88      0.89       180
weighted avg       0.92      0.92      0.91       180

